### ISSUE TITLE
Creating emtpy cards is possible

### ISSUE THREAD

**Issue by martyschaer** [severinkaderli/memento#1] opened 2015-09-09 13:05 UTC
name says it. One may create empty cards by clicking the "create" button without entering any information.

**Comment by severinkaderli** [comment] 2015-09-11 09:47
Gonna take a look at this issue over the weekend. The Problem is that I'm not validating any forms for invalid input except the login and registering form.

**Comment by severinkaderli** [comment] 2015-09-12 17:37
Well the bug is now fixed and there should be form validation in every form now, with nice looking error messages :)

**Closed as completed by severinkaderli** 2015-09-12 17:37 UTC
Labels: bug
